environment:
  matrix:
    - nodejs_version: "4.2"

install:
  - git rev-parse HEAD
  - ps: Install-Product node $env:nodejs_version
  - npm version
  - npm install

cache:
  - '%APPDATA%\npm-cache'

build: off

test_script:
  - npm version
  - cmd: npm run ci

