environment:
  matrix:
    - nodejs_version: "4.2"

install:
  - git rev-parse HEAD
  - ps: Install-Product node $env:nodejs_version
  - npm version
  - npm install -g yarnpkg
  - yarn
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

build: off

before_test:
  - yarn -v
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
  - cmd: yarn run ci

